
export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions with zero fees.',
    description: 'Get access to our exclusive app that allows you to send unlimited transcations without getting charged any fees.',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/webilo-about.svg').default,
    alt: 'About Webilo',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions with zero fees.',
    description: 'Get access to our exclusive app that allows you to send unlimited transcations without getting charged any fees.',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../images/webilo-services.svg').default,
    alt: 'About Webilo',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'contact',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions with zero fees.',
    description: 'Get access to our exclusive app that allows you to send unlimited transcations without getting charged any fees.',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require("../../images/webilo-contact.svg").default,
    alt: 'About Webilo',
    dark: false,
    primary: false,
    darkText: true,
};